# coding: utf-8

"""
    CityPay Payment API

     This CityPay API is a HTTP RESTful payment API used for direct server to server transactional processing. It provides a number of payment mechanisms including: Internet, MOTO, Continuous Authority transaction processing, 3-D Secure decision handling using RFA Secure, Authorisation, Refunding, Pre-Authorisation, Cancellation/Voids and Completion processing. The API is also capable of tokinsed payments using Card Holder Accounts.  ## Compliance and Security Your application will need to adhere to PCI-DSS standards to operate safely and to meet requirements set out by  Visa and MasterCard and the PCI Security Standards Council. These include  * Data must be collected using TLS version 1.2 using [strong cryptography](#enabled-tls-ciphers). We will not accept calls to our API at   lower grade encryption levels. We regularly scan our TLS endpoints for vulnerabilities and perform TLS assessments   as part of our compliance program. * The application must not store sensitive card holder data (CHD) such as the card security code (CSC) or   primary access number (PAN) * The application must not display the full card number on receipts, it is recommended to mask the PAN   and show the last 4 digits. The API will return this for you for ease of receipt creation * If you are developing a website, you will be required to perform regular scans on the network where you host the   application to meet your compliance obligations * You will be required to be PCI Compliant and the application must adhere to the security standard. Further information   is available from [https://www.pcisecuritystandards.org/](https://www.pcisecuritystandards.org/) * The API verifies that the request is for a valid account and originates from a trusted source using the remote IP   address. Our application firewalls analyse data that may be an attempt to break a large number of security common   security vulnerabilities.   # noqa: E501

    Contact: support@citypay.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from citypay import schemas  # noqa: F401


class AuthRequest(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "identifier",
            "amount",
            "merchantid",
            "expmonth",
            "expyear",
            "cardnumber",
        }
        
        class properties:
            
            
            class amount(
                schemas.Int32Schema
            ):
            
            
                class MetaOapg:
                    format = 'int32'
            
            
            class cardnumber(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 22
                    min_length = 12
            
            
            class expmonth(
                schemas.Int32Schema
            ):
            
            
                class MetaOapg:
                    format = 'int32'
                    inclusive_maximum = 12
                    inclusive_minimum = 1
            
            
            class expyear(
                schemas.Int32Schema
            ):
            
            
                class MetaOapg:
                    format = 'int32'
                    inclusive_maximum = 2100
                    inclusive_minimum = 2000
            
            
            class identifier(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 50
                    min_length = 4
            merchantid = schemas.Int32Schema
        
            @staticmethod
            def airline_data() -> typing.Type['AirlineAdvice']:
                return AirlineAdvice
            avs_postcode_policy = schemas.StrSchema
        
            @staticmethod
            def bill_to() -> typing.Type['ContactDetails']:
                return ContactDetails
            
            
            class csc(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 4
                    min_length = 3
            csc_policy = schemas.StrSchema
            
            
            class currency(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 3
                    min_length = 3
            duplicate_policy = schemas.StrSchema
        
            @staticmethod
            def event_management() -> typing.Type['EventDataModel']:
                return EventDataModel
        
            @staticmethod
            def external_mpi() -> typing.Type['ExternalMPI']:
                return ExternalMPI
            match_avsa = schemas.StrSchema
        
            @staticmethod
            def mcc6012() -> typing.Type['MCC6012']:
                return MCC6012
            
            
            class name_on_card(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 45
                    min_length = 2
        
            @staticmethod
            def ship_to() -> typing.Type['ContactDetails']:
                return ContactDetails
        
            @staticmethod
            def threedsecure() -> typing.Type['ThreeDSecure']:
                return ThreeDSecure
            
            
            class trans_info(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 50
            
            
            class trans_type(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 1
            __annotations__ = {
                "amount": amount,
                "cardnumber": cardnumber,
                "expmonth": expmonth,
                "expyear": expyear,
                "identifier": identifier,
                "merchantid": merchantid,
                "airline_data": airline_data,
                "avs_postcode_policy": avs_postcode_policy,
                "bill_to": bill_to,
                "csc": csc,
                "csc_policy": csc_policy,
                "currency": currency,
                "duplicate_policy": duplicate_policy,
                "event_management": event_management,
                "external_mpi": external_mpi,
                "match_avsa": match_avsa,
                "mcc6012": mcc6012,
                "name_on_card": name_on_card,
                "ship_to": ship_to,
                "threedsecure": threedsecure,
                "trans_info": trans_info,
                "trans_type": trans_type,
            }
    
    identifier: MetaOapg.properties.identifier
    amount: MetaOapg.properties.amount
    merchantid: MetaOapg.properties.merchantid
    expmonth: MetaOapg.properties.expmonth
    expyear: MetaOapg.properties.expyear
    cardnumber: MetaOapg.properties.cardnumber
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cardnumber"]) -> MetaOapg.properties.cardnumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["expmonth"]) -> MetaOapg.properties.expmonth: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["expyear"]) -> MetaOapg.properties.expyear: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["identifier"]) -> MetaOapg.properties.identifier: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["merchantid"]) -> MetaOapg.properties.merchantid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["airline_data"]) -> 'AirlineAdvice': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["avs_postcode_policy"]) -> MetaOapg.properties.avs_postcode_policy: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bill_to"]) -> 'ContactDetails': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["csc"]) -> MetaOapg.properties.csc: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["csc_policy"]) -> MetaOapg.properties.csc_policy: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["currency"]) -> MetaOapg.properties.currency: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["duplicate_policy"]) -> MetaOapg.properties.duplicate_policy: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["event_management"]) -> 'EventDataModel': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["external_mpi"]) -> 'ExternalMPI': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["match_avsa"]) -> MetaOapg.properties.match_avsa: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["mcc6012"]) -> 'MCC6012': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name_on_card"]) -> MetaOapg.properties.name_on_card: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ship_to"]) -> 'ContactDetails': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["threedsecure"]) -> 'ThreeDSecure': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["trans_info"]) -> MetaOapg.properties.trans_info: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["trans_type"]) -> MetaOapg.properties.trans_type: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["amount", "cardnumber", "expmonth", "expyear", "identifier", "merchantid", "airline_data", "avs_postcode_policy", "bill_to", "csc", "csc_policy", "currency", "duplicate_policy", "event_management", "external_mpi", "match_avsa", "mcc6012", "name_on_card", "ship_to", "threedsecure", "trans_info", "trans_type", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cardnumber"]) -> MetaOapg.properties.cardnumber: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["expmonth"]) -> MetaOapg.properties.expmonth: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["expyear"]) -> MetaOapg.properties.expyear: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["identifier"]) -> MetaOapg.properties.identifier: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["merchantid"]) -> MetaOapg.properties.merchantid: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["airline_data"]) -> typing.Union['AirlineAdvice', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["avs_postcode_policy"]) -> typing.Union[MetaOapg.properties.avs_postcode_policy, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bill_to"]) -> typing.Union['ContactDetails', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["csc"]) -> typing.Union[MetaOapg.properties.csc, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["csc_policy"]) -> typing.Union[MetaOapg.properties.csc_policy, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["currency"]) -> typing.Union[MetaOapg.properties.currency, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["duplicate_policy"]) -> typing.Union[MetaOapg.properties.duplicate_policy, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["event_management"]) -> typing.Union['EventDataModel', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["external_mpi"]) -> typing.Union['ExternalMPI', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["match_avsa"]) -> typing.Union[MetaOapg.properties.match_avsa, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["mcc6012"]) -> typing.Union['MCC6012', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name_on_card"]) -> typing.Union[MetaOapg.properties.name_on_card, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ship_to"]) -> typing.Union['ContactDetails', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["threedsecure"]) -> typing.Union['ThreeDSecure', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["trans_info"]) -> typing.Union[MetaOapg.properties.trans_info, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["trans_type"]) -> typing.Union[MetaOapg.properties.trans_type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["amount", "cardnumber", "expmonth", "expyear", "identifier", "merchantid", "airline_data", "avs_postcode_policy", "bill_to", "csc", "csc_policy", "currency", "duplicate_policy", "event_management", "external_mpi", "match_avsa", "mcc6012", "name_on_card", "ship_to", "threedsecure", "trans_info", "trans_type", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        identifier: typing.Union[MetaOapg.properties.identifier, str, ],
        amount: typing.Union[MetaOapg.properties.amount, decimal.Decimal, int, ],
        merchantid: typing.Union[MetaOapg.properties.merchantid, decimal.Decimal, int, ],
        expmonth: typing.Union[MetaOapg.properties.expmonth, decimal.Decimal, int, ],
        expyear: typing.Union[MetaOapg.properties.expyear, decimal.Decimal, int, ],
        cardnumber: typing.Union[MetaOapg.properties.cardnumber, str, ],
        airline_data: typing.Union['AirlineAdvice', schemas.Unset] = schemas.unset,
        avs_postcode_policy: typing.Union[MetaOapg.properties.avs_postcode_policy, str, schemas.Unset] = schemas.unset,
        bill_to: typing.Union['ContactDetails', schemas.Unset] = schemas.unset,
        csc: typing.Union[MetaOapg.properties.csc, str, schemas.Unset] = schemas.unset,
        csc_policy: typing.Union[MetaOapg.properties.csc_policy, str, schemas.Unset] = schemas.unset,
        currency: typing.Union[MetaOapg.properties.currency, str, schemas.Unset] = schemas.unset,
        duplicate_policy: typing.Union[MetaOapg.properties.duplicate_policy, str, schemas.Unset] = schemas.unset,
        event_management: typing.Union['EventDataModel', schemas.Unset] = schemas.unset,
        external_mpi: typing.Union['ExternalMPI', schemas.Unset] = schemas.unset,
        match_avsa: typing.Union[MetaOapg.properties.match_avsa, str, schemas.Unset] = schemas.unset,
        mcc6012: typing.Union['MCC6012', schemas.Unset] = schemas.unset,
        name_on_card: typing.Union[MetaOapg.properties.name_on_card, str, schemas.Unset] = schemas.unset,
        ship_to: typing.Union['ContactDetails', schemas.Unset] = schemas.unset,
        threedsecure: typing.Union['ThreeDSecure', schemas.Unset] = schemas.unset,
        trans_info: typing.Union[MetaOapg.properties.trans_info, str, schemas.Unset] = schemas.unset,
        trans_type: typing.Union[MetaOapg.properties.trans_type, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AuthRequest':
        return super().__new__(
            cls,
            *args,
            identifier=identifier,
            amount=amount,
            merchantid=merchantid,
            expmonth=expmonth,
            expyear=expyear,
            cardnumber=cardnumber,
            airline_data=airline_data,
            avs_postcode_policy=avs_postcode_policy,
            bill_to=bill_to,
            csc=csc,
            csc_policy=csc_policy,
            currency=currency,
            duplicate_policy=duplicate_policy,
            event_management=event_management,
            external_mpi=external_mpi,
            match_avsa=match_avsa,
            mcc6012=mcc6012,
            name_on_card=name_on_card,
            ship_to=ship_to,
            threedsecure=threedsecure,
            trans_info=trans_info,
            trans_type=trans_type,
            _configuration=_configuration,
            **kwargs,
        )

from citypay.model.airline_advice import AirlineAdvice
from citypay.model.contact_details import ContactDetails
from citypay.model.event_data_model import EventDataModel
from citypay.model.external_mpi import ExternalMPI
from citypay.model.mcc6012 import MCC6012
from citypay.model.three_d_secure import ThreeDSecure
