# coding: utf-8

"""
    CityPay Payment API

     This CityPay API is a HTTP RESTful payment API used for direct server to server transactional processing. It provides a number of payment mechanisms including: Internet, MOTO, Continuous Authority transaction processing, 3-D Secure decision handling using RFA Secure, Authorisation, Refunding, Pre-Authorisation, Cancellation/Voids and Completion processing. The API is also capable of tokinsed payments using Card Holder Accounts.  ## Compliance and Security Your application will need to adhere to PCI-DSS standards to operate safely and to meet requirements set out by  Visa and MasterCard and the PCI Security Standards Council. These include  * Data must be collected using TLS version 1.2 using [strong cryptography](#enabled-tls-ciphers). We will not accept calls to our API at   lower grade encryption levels. We regularly scan our TLS endpoints for vulnerabilities and perform TLS assessments   as part of our compliance program. * The application must not store sensitive card holder data (CHD) such as the card security code (CSC) or   primary access number (PAN) * The application must not display the full card number on receipts, it is recommended to mask the PAN   and show the last 4 digits. The API will return this for you for ease of receipt creation * If you are developing a website, you will be required to perform regular scans on the network where you host the   application to meet your compliance obligations * You will be required to be PCI Compliant and the application must adhere to the security standard. Further information   is available from [https://www.pcisecuritystandards.org/](https://www.pcisecuritystandards.org/) * The API verifies that the request is for a valid account and originates from a trusted source using the remote IP   address. Our application firewalls analyse data that may be an attempt to break a large number of security common   security vulnerabilities.   # noqa: E501

    Contact: support@citypay.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from citypay import schemas  # noqa: F401


class MCC6012(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            recipient_account = schemas.StrSchema
            recipient_dob = schemas.StrSchema
            recipient_lastname = schemas.StrSchema
            recipient_postcode = schemas.StrSchema
            __annotations__ = {
                "recipient_account": recipient_account,
                "recipient_dob": recipient_dob,
                "recipient_lastname": recipient_lastname,
                "recipient_postcode": recipient_postcode,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["recipient_account"]) -> MetaOapg.properties.recipient_account: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["recipient_dob"]) -> MetaOapg.properties.recipient_dob: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["recipient_lastname"]) -> MetaOapg.properties.recipient_lastname: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["recipient_postcode"]) -> MetaOapg.properties.recipient_postcode: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["recipient_account", "recipient_dob", "recipient_lastname", "recipient_postcode", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["recipient_account"]) -> typing.Union[MetaOapg.properties.recipient_account, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["recipient_dob"]) -> typing.Union[MetaOapg.properties.recipient_dob, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["recipient_lastname"]) -> typing.Union[MetaOapg.properties.recipient_lastname, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["recipient_postcode"]) -> typing.Union[MetaOapg.properties.recipient_postcode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["recipient_account", "recipient_dob", "recipient_lastname", "recipient_postcode", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        recipient_account: typing.Union[MetaOapg.properties.recipient_account, str, schemas.Unset] = schemas.unset,
        recipient_dob: typing.Union[MetaOapg.properties.recipient_dob, str, schemas.Unset] = schemas.unset,
        recipient_lastname: typing.Union[MetaOapg.properties.recipient_lastname, str, schemas.Unset] = schemas.unset,
        recipient_postcode: typing.Union[MetaOapg.properties.recipient_postcode, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'MCC6012':
        return super().__new__(
            cls,
            *args,
            recipient_account=recipient_account,
            recipient_dob=recipient_dob,
            recipient_lastname=recipient_lastname,
            recipient_postcode=recipient_postcode,
            _configuration=_configuration,
            **kwargs,
        )
