# coding: utf-8

"""
    CityPay Payment API

     This CityPay API is a HTTP RESTful payment API used for direct server to server transactional processing. It provides a number of payment mechanisms including: Internet, MOTO, Continuous Authority transaction processing, 3-D Secure decision handling using RFA Secure, Authorisation, Refunding, Pre-Authorisation, Cancellation/Voids and Completion processing. The API is also capable of tokinsed payments using Card Holder Accounts.  ## Compliance and Security Your application will need to adhere to PCI-DSS standards to operate safely and to meet requirements set out by  Visa and MasterCard and the PCI Security Standards Council. These include  * Data must be collected using TLS version 1.2 using [strong cryptography](#enabled-tls-ciphers). We will not accept calls to our API at   lower grade encryption levels. We regularly scan our TLS endpoints for vulnerabilities and perform TLS assessments   as part of our compliance program. * The application must not store sensitive card holder data (CHD) such as the card security code (CSC) or   primary access number (PAN) * The application must not display the full card number on receipts, it is recommended to mask the PAN   and show the last 4 digits. The API will return this for you for ease of receipt creation * If you are developing a website, you will be required to perform regular scans on the network where you host the   application to meet your compliance obligations * You will be required to be PCI Compliant and the application must adhere to the security standard. Further information   is available from [https://www.pcisecuritystandards.org/](https://www.pcisecuritystandards.org/) * The API verifies that the request is for a valid account and originates from a trusted source using the remote IP   address. Our application firewalls analyse data that may be an attempt to break a large number of security common   security vulnerabilities.   # noqa: E501

    Contact: support@citypay.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from citypay import schemas  # noqa: F401


class PaylinkCart(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            
            
            class contents(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['PaylinkCartItemModel']:
                        return PaylinkCartItemModel
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['PaylinkCartItemModel'], typing.List['PaylinkCartItemModel']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'contents':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'PaylinkCartItemModel':
                    return super().__getitem__(i)
            coupon = schemas.StrSchema
            mode = schemas.Int32Schema
            product_description = schemas.StrSchema
            product_information = schemas.StrSchema
            shipping = schemas.Int32Schema
            tax = schemas.Int32Schema
            __annotations__ = {
                "contents": contents,
                "coupon": coupon,
                "mode": mode,
                "product_description": product_description,
                "product_information": product_information,
                "shipping": shipping,
                "tax": tax,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["contents"]) -> MetaOapg.properties.contents: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["coupon"]) -> MetaOapg.properties.coupon: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["mode"]) -> MetaOapg.properties.mode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["product_description"]) -> MetaOapg.properties.product_description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["product_information"]) -> MetaOapg.properties.product_information: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["shipping"]) -> MetaOapg.properties.shipping: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tax"]) -> MetaOapg.properties.tax: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["contents", "coupon", "mode", "product_description", "product_information", "shipping", "tax", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["contents"]) -> typing.Union[MetaOapg.properties.contents, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["coupon"]) -> typing.Union[MetaOapg.properties.coupon, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["mode"]) -> typing.Union[MetaOapg.properties.mode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["product_description"]) -> typing.Union[MetaOapg.properties.product_description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["product_information"]) -> typing.Union[MetaOapg.properties.product_information, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["shipping"]) -> typing.Union[MetaOapg.properties.shipping, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tax"]) -> typing.Union[MetaOapg.properties.tax, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["contents", "coupon", "mode", "product_description", "product_information", "shipping", "tax", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        contents: typing.Union[MetaOapg.properties.contents, list, tuple, schemas.Unset] = schemas.unset,
        coupon: typing.Union[MetaOapg.properties.coupon, str, schemas.Unset] = schemas.unset,
        mode: typing.Union[MetaOapg.properties.mode, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        product_description: typing.Union[MetaOapg.properties.product_description, str, schemas.Unset] = schemas.unset,
        product_information: typing.Union[MetaOapg.properties.product_information, str, schemas.Unset] = schemas.unset,
        shipping: typing.Union[MetaOapg.properties.shipping, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        tax: typing.Union[MetaOapg.properties.tax, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PaylinkCart':
        return super().__new__(
            cls,
            *args,
            contents=contents,
            coupon=coupon,
            mode=mode,
            product_description=product_description,
            product_information=product_information,
            shipping=shipping,
            tax=tax,
            _configuration=_configuration,
            **kwargs,
        )

from citypay.model.paylink_cart_item_model import PaylinkCartItemModel
