# coding: utf-8

"""
    CityPay Payment API

     This CityPay API is a HTTP RESTful payment API used for direct server to server transactional processing. It provides a number of payment mechanisms including: Internet, MOTO, Continuous Authority transaction processing, 3-D Secure decision handling using RFA Secure, Authorisation, Refunding, Pre-Authorisation, Cancellation/Voids and Completion processing. The API is also capable of tokinsed payments using Card Holder Accounts.  ## Compliance and Security Your application will need to adhere to PCI-DSS standards to operate safely and to meet requirements set out by  Visa and MasterCard and the PCI Security Standards Council. These include  * Data must be collected using TLS version 1.2 using [strong cryptography](#enabled-tls-ciphers). We will not accept calls to our API at   lower grade encryption levels. We regularly scan our TLS endpoints for vulnerabilities and perform TLS assessments   as part of our compliance program. * The application must not store sensitive card holder data (CHD) such as the card security code (CSC) or   primary access number (PAN) * The application must not display the full card number on receipts, it is recommended to mask the PAN   and show the last 4 digits. The API will return this for you for ease of receipt creation * If you are developing a website, you will be required to perform regular scans on the network where you host the   application to meet your compliance obligations * You will be required to be PCI Compliant and the application must adhere to the security standard. Further information   is available from [https://www.pcisecuritystandards.org/](https://www.pcisecuritystandards.org/) * The API verifies that the request is for a valid account and originates from a trusted source using the remote IP   address. Our application firewalls analyse data that may be an attempt to break a large number of security common   security vulnerabilities.   # noqa: E501

    Contact: support@citypay.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from citypay import schemas  # noqa: F401


class PaylinkBillPaymentTokenRequest(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "request",
        }
        
        class properties:
        
            @staticmethod
            def request() -> typing.Type['PaylinkTokenRequestModel']:
                return PaylinkTokenRequestModel
            addressee = schemas.StrSchema
            
            
            class attachments(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['PaylinkAttachmentRequest']:
                        return PaylinkAttachmentRequest
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['PaylinkAttachmentRequest'], typing.List['PaylinkAttachmentRequest']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'attachments':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'PaylinkAttachmentRequest':
                    return super().__getitem__(i)
            descriptor = schemas.StrSchema
            due = schemas.DateSchema
        
            @staticmethod
            def email_notification_path() -> typing.Type['PaylinkEmailNotificationPath']:
                return PaylinkEmailNotificationPath
            memo = schemas.StrSchema
        
            @staticmethod
            def sms_notification_path() -> typing.Type['PaylinkSMSNotificationPath']:
                return PaylinkSMSNotificationPath
            __annotations__ = {
                "request": request,
                "addressee": addressee,
                "attachments": attachments,
                "descriptor": descriptor,
                "due": due,
                "email_notification_path": email_notification_path,
                "memo": memo,
                "sms_notification_path": sms_notification_path,
            }
    
    request: 'PaylinkTokenRequestModel'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["request"]) -> 'PaylinkTokenRequestModel': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["addressee"]) -> MetaOapg.properties.addressee: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["attachments"]) -> MetaOapg.properties.attachments: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["descriptor"]) -> MetaOapg.properties.descriptor: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["due"]) -> MetaOapg.properties.due: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["email_notification_path"]) -> 'PaylinkEmailNotificationPath': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["memo"]) -> MetaOapg.properties.memo: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sms_notification_path"]) -> 'PaylinkSMSNotificationPath': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["request", "addressee", "attachments", "descriptor", "due", "email_notification_path", "memo", "sms_notification_path", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["request"]) -> 'PaylinkTokenRequestModel': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["addressee"]) -> typing.Union[MetaOapg.properties.addressee, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["attachments"]) -> typing.Union[MetaOapg.properties.attachments, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["descriptor"]) -> typing.Union[MetaOapg.properties.descriptor, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["due"]) -> typing.Union[MetaOapg.properties.due, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["email_notification_path"]) -> typing.Union['PaylinkEmailNotificationPath', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["memo"]) -> typing.Union[MetaOapg.properties.memo, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sms_notification_path"]) -> typing.Union['PaylinkSMSNotificationPath', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["request", "addressee", "attachments", "descriptor", "due", "email_notification_path", "memo", "sms_notification_path", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        request: 'PaylinkTokenRequestModel',
        addressee: typing.Union[MetaOapg.properties.addressee, str, schemas.Unset] = schemas.unset,
        attachments: typing.Union[MetaOapg.properties.attachments, list, tuple, schemas.Unset] = schemas.unset,
        descriptor: typing.Union[MetaOapg.properties.descriptor, str, schemas.Unset] = schemas.unset,
        due: typing.Union[MetaOapg.properties.due, str, date, schemas.Unset] = schemas.unset,
        email_notification_path: typing.Union['PaylinkEmailNotificationPath', schemas.Unset] = schemas.unset,
        memo: typing.Union[MetaOapg.properties.memo, str, schemas.Unset] = schemas.unset,
        sms_notification_path: typing.Union['PaylinkSMSNotificationPath', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PaylinkBillPaymentTokenRequest':
        return super().__new__(
            cls,
            *args,
            request=request,
            addressee=addressee,
            attachments=attachments,
            descriptor=descriptor,
            due=due,
            email_notification_path=email_notification_path,
            memo=memo,
            sms_notification_path=sms_notification_path,
            _configuration=_configuration,
            **kwargs,
        )

from citypay.model.paylink_attachment_request import PaylinkAttachmentRequest
from citypay.model.paylink_email_notification_path import PaylinkEmailNotificationPath
from citypay.model.paylink_sms_notification_path import PaylinkSMSNotificationPath
from citypay.model.paylink_token_request_model import PaylinkTokenRequestModel
