# coding: utf-8

"""
    CityPay Payment API

     This CityPay API is an HTTP RESTful payment API used for direct server to server transactional processing. It provides a number of payment mechanisms including: Internet, MOTO, Continuous Authority transaction processing, 3-D Secure decision handling using RFA Secure, Authorisation, Refunding, Pre-Authorisation, Cancellation/Voids and Completion processing. The API is also capable of tokenized payments using cardholder Accounts.  ## Compliance and Security Your application will need to adhere to PCI-DSS standards to operate safely and to meet requirements set out by  Visa and MasterCard and the PCI Security Standards Council. These include  * Data must be collected using TLS version 1.2 using [strong cryptography](https://citypay.github.io/api-docs/payment-api/#enabled-tls-ciphers). We will not accept calls to our API at   lower grade encryption levels. We regularly scan our TLS endpoints for vulnerabilities and perform TLS assessments   as part of our compliance program. * The application must not store sensitive cardholder data (CHD) such as the card security code (CSC) or   primary access number (PAN) * The application must not display the full card number on receipts, it is recommended to mask the PAN   and show the last 4 digits. The API will return this for you for ease of receipt creation * If you are developing a website, you will be required to perform regular scans on the network where you host the   application to meet your compliance obligations * You will be required to be PCI Compliant and the application must adhere to the security standard. Further information   is available from [https://www.pcisecuritystandards.org/](https://www.pcisecuritystandards.org/) * The API verifies that the request is for a valid account and originates from a trusted source using the remote IP   address. Our application firewalls analyse data that may be an attempt to break a large number of security common   security vulnerabilities. 

    Contact: support@citypay.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictInt, StrictStr
from pydantic import Field
from citypay.models.paylink_custom_param import PaylinkCustomParam
from citypay.models.paylink_field_guard_model import PaylinkFieldGuardModel
from citypay.models.paylink_part_payments import PaylinkPartPayments
from citypay.models.paylink_ui import PaylinkUI
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PaylinkConfig(BaseModel):
    """
    PaylinkConfig
    """ # noqa: E501
    acs_mode: Optional[StrictStr] = Field(default=None, description="Specifies the approach to be adopted by the Paylink form when displaying a 3-D Secure challenge window. The values may be  iframe: shows the 3-D Secure ACS in an iframe dialog, neatly embedding it in Paylink. This provides a more seamless flow for the cardholder who is able to validate and authenticate their card using a dialog provided by their card issuer.  inline: an inline mode transfers the full browser window to the authentication server, allowing the payment cardholder to see their payment card issuer's URL and the certificate status in the browser. If you request an iframe mode and the browser width is deemed as being small (< 768px) then an inline mode will be enforced. This is to ensure that mobile users have an improved user experience. ")
    custom_params: Optional[List[PaylinkCustomParam]] = None
    descriptor: Optional[StrictStr] = Field(default=None, description="Directly specify the merchant descriptor used for the transaction to be displayed on the payment page.")
    expire_in: Optional[StrictStr] = Field(default=None, description="Specifies a period of time in seconds after which the token cannot be used. A value of 0 defines that the token will never expire. The API will convert an expiry time based on a string value. For instance:   s - Time in seconds, for example 90s.   m - Time in minutes, for example 20m.   h - Time in hours, for example 4h.   w - Time in weeks, for example 4w.   M - Time in months, for example 6M.   y - Time in years, for example 1y.   Defaults to 30 minutes. ")
    field_guard: Optional[List[PaylinkFieldGuardModel]] = None
    lock_params: Optional[List[StrictStr]] = None
    merch_logo: Optional[StrictStr] = Field(default=None, description="A URL of a logo to include in the form. The URL should be delivered using HTTPS.")
    merch_terms: Optional[StrictStr] = Field(default=None, description="A URL of the merchant terms and conditions for payment. If a value is supplied, a checkbox will be required to be completed to confirm that the cardholder agrees to these conditions before payment. A modal dialogue is displayed with the content of the conditions displayed.")
    options: Optional[List[StrictStr]] = None
    part_payments: Optional[PaylinkPartPayments] = None
    pass_through_data: Optional[Dict[str, StrictStr]] = None
    pass_through_headers: Optional[Dict[str, StrictStr]] = None
    postback: Optional[StrictStr] = Field(default=None, description="Specifies a URL to use for a call back when the payment is completed. see Postback Handling }.")
    postback_password: Optional[StrictStr] = Field(default=None, description="A password to be added to the postback for HTTP Basic Authentication.")
    postback_policy: Optional[StrictStr] = Field(default=None, description="The policy setting for the postback see Postback Handling.")
    postback_username: Optional[StrictStr] = Field(default=None, description="A username to be added to the postback for HTTP Basic Authentication.")
    redirect_delay: Optional[StrictInt] = Field(default=None, description="A value which can delay the redirection in seconds. A value of 0 will redirect immediately.")
    redirect_failure: Optional[StrictStr] = Field(default=None, description="A URL which the browser is redirected to on non-completion of a transaction.")
    redirect_success: Optional[StrictStr] = Field(default=None, description="A URL which the browser is redirected to on authorisation of a transaction.")
    renderer: Optional[StrictStr] = Field(default=None, description="The Paylink renderer engine to use.")
    return_params: Optional[StrictBool] = Field(default=None, description="If a value of true is specified, any redirection will include the transaction result in parameters. It is recommended to use the postback integration rather than redirection parameters.")
    ui: Optional[PaylinkUI] = None
    __properties: ClassVar[List[str]] = ["acs_mode", "custom_params", "descriptor", "expire_in", "field_guard", "lock_params", "merch_logo", "merch_terms", "options", "part_payments", "pass_through_data", "pass_through_headers", "postback", "postback_password", "postback_policy", "postback_username", "redirect_delay", "redirect_failure", "redirect_success", "renderer", "return_params", "ui"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PaylinkConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in custom_params (list)
        _items = []
        if self.custom_params:
            for _item in self.custom_params:
                if _item:
                    _items.append(_item.to_dict())
            _dict['custom_params'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in field_guard (list)
        _items = []
        if self.field_guard:
            for _item in self.field_guard:
                if _item:
                    _items.append(_item.to_dict())
            _dict['field_guard'] = _items
        # override the default output from pydantic by calling `to_dict()` of part_payments
        if self.part_payments:
            _dict['part_payments'] = self.part_payments.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ui
        if self.ui:
            _dict['ui'] = self.ui.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of PaylinkConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "acs_mode": obj.get("acs_mode"),
            "custom_params": [PaylinkCustomParam.from_dict(_item) for _item in obj.get("custom_params")] if obj.get("custom_params") is not None else None,
            "descriptor": obj.get("descriptor"),
            "expire_in": obj.get("expire_in"),
            "field_guard": [PaylinkFieldGuardModel.from_dict(_item) for _item in obj.get("field_guard")] if obj.get("field_guard") is not None else None,
            "lock_params": obj.get("lock_params"),
            "merch_logo": obj.get("merch_logo"),
            "merch_terms": obj.get("merch_terms"),
            "options": obj.get("options"),
            "part_payments": PaylinkPartPayments.from_dict(obj.get("part_payments")) if obj.get("part_payments") is not None else None,
            "pass_through_data": obj.get("pass_through_data"),
            "pass_through_headers": obj.get("pass_through_headers"),
            "postback": obj.get("postback"),
            "postback_password": obj.get("postback_password"),
            "postback_policy": obj.get("postback_policy"),
            "postback_username": obj.get("postback_username"),
            "redirect_delay": obj.get("redirect_delay"),
            "redirect_failure": obj.get("redirect_failure"),
            "redirect_success": obj.get("redirect_success"),
            "renderer": obj.get("renderer"),
            "return_params": obj.get("return_params"),
            "ui": PaylinkUI.from_dict(obj.get("ui")) if obj.get("ui") is not None else None
        })
        return _obj


